services:

  notebook:
    build:
      context: .
      target: "${WENDY_IMAGE_BUILD_TARGET:-development}"
      args:
        DOCKER_USER: ${DOCKER_USER:-1000}
    user: ${DOCKER_USER:-1000}
    environment:
      NB_UID: ${DOCKER_UID:-1000}
      NB_GID: ${DOCKER_GID:-1000}
      CHOWN_HOME: 'yes'
      CHOWN_HOME_OPTS: -R
    group_add:
      - users
    ports:
      - 8080:8888
    volumes:
      - ./wendy:/home/jovyan/work
